### ISSUE TITLE
Python 2.7 compatibility?

### ISSUE THREAD

**Issue by twardoch** [TiroTypeworks/TiroTools#3]
I’m getting a relatively trivial-to-fix failure when trying to install Volto with pip2 (Python 2.7): 

```
with open("README.md", encoding="utf-8") as readme:
    TypeError: 'encoding' is an invalid keyword argument for this function
``` 

Full log. With pip3 (Python 3) it installs OK. 
I know, end of life etc. 

```
[16:54:40] $ pip2 install --user --upgrade git+https://github.com/TiroTypeworks/Volto
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting git+https://github.com/TiroTypeworks/Volto
  Cloning https://github.com/TiroTypeworks/Volto to /private/var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/pip-req-build-_HSlhQ
  Running command git clone -q https://github.com/TiroTypeworks/Volto /private/var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/pip-req-build-_HSlhQ
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/pip-req-build-_HSlhQ/setup.py", line 3, in <module>
        with open("README.md", encoding="utf-8") as readme:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/pip-req-build-_HSlhQ/
~/Developer/vcs/github.twardoch/pub/fontsurgery-tools/macOS/modules

[16:55:01] $ pip3 install --user --upgrade git+https://github.com/TiroTypeworks/Volto
Collecting git+https://github.com/TiroTypeworks/Volto
  Cloning https://github.com/TiroTypeworks/Volto to /private/var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/pip-req-build-qjiau1vf
Requirement already satisfied, skipping upgrade: fonttools>=3.40.0 in /Users/adam/Library/Python/3.7/lib/python/site-packages (from Volto==0.1.0) (3.40.0)
Building wheels for collected packages: Volto
  Building wheel for Volto (setup.py) ... done
  Stored in directory: /private/var/folders/xl/xzdty8fj5db_9d8s_f6178m40000gn/T/pip-ephem-wheel-cache-dzcqeam3/wheels/28/7c/bb/377a8a81401ca92bbdb355efcdcb5e489ccf5886a944fbdb86
Successfully built Volto
Installing collected packages: Volto
  Found existing installation: Volto 0.1.0
    Uninstalling Volto-0.1.0:
      Successfully uninstalled Volto-0.1.0
Successfully installed Volto-0.1.0
```

**Comment by anthrotype** [comment]
Readme says it requires python 3

**Comment by khaledhosny** [comment]
Yes, Python 3 is required and the code will need more changes to work under Python 2.

**Comment by twardoch** [comment]
OK, I see, thanks!
